version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: prato-pronto-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_prato_pronto
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
    driver: bridge